### PR TITLE
Pointer cursor > selection cursor for links

### PR DESCRIPTION
**Pull request by ChrisLane**

### CODE REVIEW

**Comment by frebib** [comment]
I'm actually surprised that this isn't default honestly. Is there some overriding CSS that breaks the default styles?

**Comment by ChrisLane** [comment]
Now you see I thought it was default too, looking at other sites, it's taken from "a:-webkit-any-link" (on chrome) and the cursor is set to auto. Couldn't find what is changing the behaviour but this is a quick override fix.

**Comment by ChrisLane** [comment]
Ah, I think it's because it defaults to auto and the buttons "Flag as wrong" and "continue" don't link to another page and so are given the selection pointer. This is why we have to set it manually.

**Comment by frebib** [comment]
I guess that makes sense. Which links are we talking about? Can you point them out in the source?

**Comment by ChrisLane** [comment]
https://github.com/mishajw/timeglo.be/blob/fd2041557d0b221a1050dd8b7faec3350ee65aa6/public/javascripts/main.js#L562

https://github.com/mishajw/timeglo.be/blob/fd2041557d0b221a1050dd8b7faec3350ee65aa6/public/javascripts/main.js#L638

**Comment by frebib** [comment]
I see what the issue is. The problem here is that the `a` tags that don't have `href` attributes don't display properly. Now while the CSS hack will fix it, IMO it's not the best fix.

[In HTML5, `<a>` tags _are_ valid without `href` attributes but as you've realised, don't get the `cursor: pointer` style applied to them.](http://stackoverflow.com/questions/5292343/is-an-anchor-tag-without-the-href-attribute-safe)

My suggestion for fixing this would be to add an empty `href="#"` attribute to all a elements as that's generally better practice

**Comment by ChrisLane** [comment]
Fairs

**Pull request closed without merging**
